routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Shop\Orders\Order;
use App\Shop\Customers\Account;
use App\Shop\Exporter\CSVExporter;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//Shipstation

Route::get('/shipstation', 'ShipstationController@export');
Route::post('/shipstation', 'ShipstationController@notify');

Route::group(['namespace' => 'Frontend'], function () {
    Route::group(['namespace' => 'Customers'], function () {
        Route::get('/orders/{token}', 'CustomerOrdersController@show')->name('orders.show');
    });
});

//Generate page
Route::get('/page/{slug}', 'PageController')->name('page');

$lock_config = env('APP_LOCK') ? ['middleware' => 'auth.basic'] : [];

/*Route::get('testnextbox', function(){

    $account  = App\Shop\Customers\Account::where('email', 'mharkrollen@gmail.com')->first();
    $order = (new App\Shop\ShoppingBoxes\ShoppingBoxBuilder($account->nextBox()))->setData(['status' => App\Shop\Orders\Order::ORDER_PROCESSING])->build();
    event(new App\Events\OrderCreated($order));
});*/
/*Route::get('testgiftcard', function(){

    $order  = App\Shop\Orders\Order::find(10007);
    Mail::to($order)->send(new App\Mail\GiftCard($order, App\Shop\Discounts\GiftCard::find(1)));

    //$order = App\Shop\Orders\Order::find(10007);

    //$order->processGiftCards();

});*/

/*Route::get('/testmail', function(){	
    return new App\Mail\OrderProcessed(App\Shop\Orders\Order::first());	
});

Route::get('/teststamped', function(){	
    $stamped = new App\Shop\Conversion\Stamped();
    $conversion = new App\Shop\Checkout\ConversionTracker(Order::first());
    $stamped->track($conversion->stamped());
});*/

Route::group(['middleware' => $lock_config], function () {

/** ADMIN */
    Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/admin/login', 'Auth\LoginController@login');
    Route::post('/admin/logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
    Route::get('/admin/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/admin/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/admin/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/admin/password/reset', 'Auth\ResetPasswordController@reset');
    Route::get('/search', 'SearchController@search');

/** END ADMIN */

    Route::group(['middleware' => ['auth', 'role:super-admin', 'ip_address'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
        Route::namespace ('Administrators')->group(function () {

            Route::get('/search/administrators', 'AdministratorsController@search');
            Route::post('/administrators/adduser', 'AdministratorsController@adduser')->name('administrators.adduser');
            Route::post('/administrators/store', 'AdministratorsController@store')->name('administrators.store');            
            Route::get('/administrators/{user}', 'AdministratorsController@detail')->name('dashboard');
            Route::patch('/administrators/{user}', 'AdministratorsController@update')->name('dashboard');
            Route::delete('/administrators/{$user}', 'AdministratorsController@destroy')->name('administrators.delete');

        });

    });

    Route::group(['middleware' => ['auth', 'role:super-admin|admin', 'ip_address'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

        Route::get('/testmail/{day}', function($day){

            $account = App\Shop\Customers\Account::first();
            switch ($day) {
                case 1:
                    return new App\Mail\FailedPaymentCharge($account);
                    break;
                case 2:
                    return new App\Mail\FailedPaymentCharge2($account);
                    break;
                case 3:
                    return new App\Mail\FailedPaymentCharge3($account);
                    break;
                case 4:
                    return new App\Mail\FailedPaymentCharge4($account);
                    break;
                case 5:
                    return new App\Mail\FailedPaymentCharge5($account);
                    break;
                case 6:
                    return new App\Mail\FailedPaymentCharge6($account);
                    break;

            }	
        });

        Route::namespace ('Discounts')->group(function () {
            Route::get('/discounts/search', 'DiscountsController@search')->name('admin.discounts.search');
            Route::get('/discounts/download/{filename}', 'DiscountsController@downloadDiscounts');
            Route::resource('discounts', 'DiscountsController');
        });

        Route::namespace('Recipes')->group(function (){
            Route::get('/recipes/search', 'RecipeController@search')->name('admin.recipes.search');
            Route::resource('/recipes', 'RecipeController');
        });

        Route::namespace ('Importer')->group(function () {

            Route::get('/import/productids', 'ImporterController@productids');
            Route::get('/import/update', 'ImporterController@update');
        });

        Route::namespace ('Customers')->group(function () {
            Route::get('/customers', 'CustomersController@index')->name('customers.index');
            Route::get('/customers/settings', 'CustomersController@settings')->name('customers.settings');
            Route::post('/customers', 'CustomersController@store')->name('customers.store');
            Route::get('/customers/search', 'CustomersController@search')->name('customers.search');
            Route::get('/customers/{customer}', 'CustomersController@show')->name('customers.show');
            Route::patch('/customers/{customer}', 'CustomersController@update')->name('customers.update');
            Route::patch('/customers/{customer}/addresses', 'CustomersController@address_update')->name('customers.address_update');
            Route::delete('/customers/{customer}/addresses', 'CustomersController@address_delete')->name('customers.address_delete');
            Route::post('/customers/sendinvite/{customer}', 'CustomersController@send_invite')->name('customers.sendinvite');
            Route::post('/customers/changepassword/{customer}', 'CustomersController@changePassword')->name('customers.changepassword');
            Route::post('/customers/createaccount/{customer}', 'CustomersController@createAccount')->name('customers.createaccount');
            Route::delete('/customers/{customer}/account', 'CustomersController@disable_account')->name('customers.sendinvite');
            Route::post('/customers/{customer}/logas', 'CustomersController@loginAs');
            Route::post('/customers/{customer}/tax/upload', 'CustomersController@uploadTaxDocument');
            Route::post('/customers/{customer}/tax/exempt_toggle', 'CustomersController@exemptToggle');
            Route::get('/tax_documents/{document_id}/download', 'CustomersController@downloadTaxDocument');
            Route::delete('/tax_documents/{document_id}', 'CustomersController@deleteTaxDocument');
            //tags
            Route::patch('/customers/{customer}/tags', 'CustomersController@updateTags');
            Route::patch('/customers/{customer}/schedule', 'CustomersController@overrideSchedule');
            Route::patch('/customers/{customer}/cancel', 'CustomersController@cancelSubscription');
            Route::get('/customers/tags/search/{tag}', 'CustomersController@searchTags');
        });

        Route::namespace ('Users')->group(function () {
            Route::get('/users/search', 'UsersController@search')->name('users.search');
        });

        Route::namespace ('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::post('/products/{product}/images', 'ProductController@images')->name('products.images');
        });

        Route::namespace ('ShoppingBoxes')->group(function () {
            Route::resource('shopping-boxes', 'ShoppingBoxController');
        });

        Route::namespace ('Categories')->group(function () {
            Route::get('categories/search', 'CategoryController@search');
            Route::resource('categories', 'CategoryController');
            Route::post('/categories/{category}/images', 'CategoryController@images')->name('categories.images');
        });

        Route::namespace ('Tags')->group(function () {
            Route::resource('tags', 'TagController');
        });

        Route::namespace ('Orders')->group(function () {
            Route::get('orders/search', 'OrderAdminController@search')->name('orders.search');
            Route::get('orders/settings', 'OrderAdminController@settings')->name('orders.settings');
            Route::resource('orders', 'OrderAdminController');
            Route::post('orders/compute', 'OrderAdminController@compute')->name('orders.compute');
            Route::patch('orders/{order}/edit', 'OrderAdminController@update');
            Route::patch('orders/{order}/contact', 'OrderAdminController@update_contact');
            Route::patch('orders/{order}/referrer', 'OrderAdminController@update_referrer');
            Route::delete('orders/{order}/referrer', 'OrderAdminController@remove_referrer');
            Route::patch('orders/{order}/shipping', 'OrderAdminController@update_shipping');
            Route::patch('orders/{order}/status', 'OrderAdminController@updateStatus');

app/Http/Controllers/Admin/ShoppingBoxes/ShoppingBoxController.php
<?php

namespace App\Http\Controllers\Admin\ShoppingBoxes;

use App\Http\Controllers\Controller;
use App\Shop\ShoppingBoxes\ShoppingBox;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ShoppingBoxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $boxes = ShoppingBox::all();
        return view('admin.shoppingboxes.index', ['boxes' => $boxes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ShoppingBox  $shoppingBox
     * @return \Illuminate\Http\Response
     */
    public function show(ShoppingBox $shoppingBox)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ShoppingBox  $shoppingBox
     * @return \Illuminate\Http\Response
     */
    public function edit(ShoppingBox $shoppingBox)
    {
        return view('admin.shoppingboxes.edit', ['box' => $shoppingBox->load(['products'])]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ShoppingBox  $shoppingBox
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ShoppingBox $shoppingBox)
    {

        $shoppingBox->products()->sync($request->products);

        $recipes = collect([]);

        if ($request->has('recipes')) {
            $videos = collect($request->recipes)->map(function ($item) {

                if (Storage::exists($item['cover'])) {
                    $item['url'] = item['cover'];
                } else {
                    $item['url'] = '';
                }
                return $item;
            });
            $recipes = $videos;
        }

        $shoppingBox->update(array_merge($request->all(), ['recipes' => $recipes, 'features' => $request->features ?? []]));

        flash('Shopping box updated', 'success');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ShoppingBox  $shoppingBox
     * @return \Illuminate\Http\Response
     */
    public function destroy(ShoppingBox $shoppingBox)
    {
        //
    }
}

app/Http/Controllers/Frontend/ShoppingBoxes/ShoppingBoxController.php
<?php

namespace App\Http\Controllers\Frontend\ShoppingBoxes;

use App\Http\Controllers\Controller;
use App\Http\Resources\BoxDetail;
use App\Http\Resources\ExchangeDetail;
use App\Rules\BoxExchange;
use App\Shop\Products\Product;
use Illuminate\Http\Request;

class ShoppingBoxController extends Controller
{
    public function exchange($monthKey, Product $from, Request $request)
    {
        $box = customer()->account->futureOrders()->getMonth($monthKey);

        return new ExchangeDetail($box, $from);
    }

    public function updateAddon($monthKey, Product $product, Request $request)
    {
        $box = customer()->account->futureOrders()->getMonth($monthKey);
        $box->updateAddons($product->id, $request->qty);

        return new BoxDetail($box);
    }

    public function updateExchange($monthKey, Product $from, Request $request)
    {
        $this->validate($request, [
            'product' => [new BoxExchange($from)],
        ]);

        $box = customer()->account->futureOrders()->getMonth($monthKey);
        $box->updateExchanges($from->id, $request->product);

        return new ExchangeDetail($box, $from);
    }
}

resources/views/admin/shoppingboxes/_fields.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="col-sm-2 control-label">&nbsp;</label>
            <div class="col-sm-10">
                <MediaLibrary :image_url="'{{ $box->cover }}'" :media_id="'box-cover'">
                    <div slot="front" slot-scope="image">

                        <div class="dropzone" style="min-height:400px;">

                            <img :src="image.preview" class="" />

                            <p>Add or replace box image</p>
                            <input type="hidden" name="cover" v-model="image.cover" class="form-control" />
                        </div>

                    </div>
                </MediaLibrary>
            </div>
        </div>
        <div class="form-group"><label class="col-sm-2 control-label">Name:</label>
            <div class="col-sm-10">
                <?= Form::text('name', null, ['class' => 'form-control']) ?>
            </div>
        </div>
        <div class="form-group"><label class="col-sm-2 control-label">Key:</label>
            <div class="col-sm-10">
                <?= Form::text('key', null, ['class' => 'form-control']) ?>
            </div>
        </div>

        <div class="form-group"><label class="col-sm-2 control-label">Description:</label>
            <div class="col-sm-10">
                <?= Form::textarea('description', null, ['class' => 'form-control']) ?>
            </div>
        </div>

        <div class="form-group"><label class="col-sm-2 control-label">Available Stock:</label>
            <div class="col-sm-10">
                <?= Form::number('stock', null, ['class' => 'form-control', 'min' => 0, 'step' => 1]) ?>
            </div>
        </div>

        <div class="form-group"><label class="col-sm-2 control-label">Features:</label>
            <div class="col-sm-10">
                <Repeatable :list="{{ json_encode($box->features ?? []) }}" :blank="''">
                    <template slot="add-button" scope="props">
                                <div class="">
                                <button type="button" class="btn btn-primary btn-sm" @click="props.addItem"><i class="fa fa-plus"></i></button>
                                </div>
                            </template>
                    <template slot="list" scope="props">
                            <div class="m-t-lg m-b-lg">
                                <div class="row">
                                    
                                    <div class="col-xs-10"><input type="text" :name="'features[' + props.index +']'" v-model="props.repeatable[props.index]" class="form-control" /> </div>
                                    <div class="col-xs-2">
                                        <button type="button" class="btn btn-danger" @click="props.removeItem(props.index)"><i class="fa fa-minus"></i></button>
                                    </div>
                                </div> 
                            </div>
                        </template>
                </Repeatable>
            </div>
        </div>

    </div>

    <div class="col-sm-4">
        <div class="ibox">
            <div class="ibox-title">
                <h3>Products</h3>
            </div>
            <div class="ibox-content">
                <SearchLister :init="{{ $box->products }}" :search_url="'/admin/products'" :placeholder="'Search a product'">
                    <template slot="option" slot-scope="option">
                <div class="d-center">
                    <img :src="option.option.cover" class="img-sm" />
                    <span v-text="option.option.name"></span>
                </div>
            </template>

                    <template slot="list" slot-scope="option">
                <img :src="option.list_item.cover" class="img-sm" />
                <a href="#"><span v-text="option.list_item.name"></span></a>
                <input type="hidden" name="products[]" :value="option.list_item.id">
            </template>
                </SearchLister>
            </div>
        </div>

        <div class="ibox">
                <div class="ibox-title">
                    <h3>Video </h3>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-xs-5">
                            <MediaLibrary :image_url="'{{ $box->box_video_cover ?? '' }}'" :media_id="'box_video_cover'">
                                <div slot="front" slot-scope="image">
                                
                                <div  class="dropzone">
    
                                    <img :src="image.preview" class="" /> 
                                    
                                        <p>Add or replace box video cover</p>
                                    <input type="hidden" :name="'box_video_cover'" v-model="image.cover" class="form-control" />
                                </div> 
                                
                                </div>
                            </MediaLibrary>
                        </div>
                    <div class="col-xs-7"><input type="text" name="box_video_id" value="{{ $box->box_video_id }}" placeholder="Video ID" class="form-control" /> </div>
                    </div>
                </div>
            </div>

        <div class="ibox">
            <div class="ibox-title">
                <h3>Recipes</h3>
            </div>
            <div class="ibox-content">

                <div class="recipes">
                    <Repeatable :list="{{ $box->recipes }}" :blank="''">
                        <template slot="add-button" scope="props">
                                    <div class="text-right">
                                    <button type="button" class="btn btn-primary btn-sm" @click="props.addItem"><i class="fa fa-plus"></i> Add new recipe</button>
                                    </div>
                                </template>
                        <template slot="list" scope="props">
                                    <div class="m-t-lg m-b-lg">
                                    <div class="row">
                                        <div class="col-xs-5">
                                            <MediaLibrary :image_url="props.item.cover" :media_id="'cover' + props.index">
                                            <div slot="front" slot-scope="image">
                                            
                                            <div  class="dropzone">
                
                                                <img :src="image.preview" class="" /> 
                                                
                                                 <p>Add or replace recipe cover</p>
                                                <input type="hidden" :name="'recipes[' + props.index +'][cover]'" v-model="image.cover" class="form-control" />
                                            </div> 
                                            
                                           </div>
                                        </MediaLibrary></div>
                                        <div class="col-xs-5"><input type="text" :name="'recipes[' + props.index +'][id]'" placeholder="Video ID" v-model="props.item.id" class="form-control" /> </div>
                                        <div class="col-xs-2">
                                            <button type="button" class="btn btn-danger" @click="props.removeItem(props.index)"><i class="fa fa-minus"></i></button>
                                        </div>
                                    </div> 
                                    
                                    <div class="m-t-md">
                                        <input type="text" placeholder="Header" :name="'recipes[' + props.index +'][header]'"  v-model="props.item.header" class="form-control" />
                                    </div>
                                    <div class="m-t-md">
                                        <textarea rows="5" placeholder="Text" :name="'recipes[' + props.index +'][text]'"  v-model="props.item.text" class="form-control" ></textarea>
                                    </div>
                                

                                </div>
                            </template>
                    </Repeatable>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="hr-line-dashed"></div>
<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-8">
        <div class="text-right">
            <a href="{{ route('admin.shopping-boxes.index') }}" class="btn btn-white" type="submit">Cancel</a>
            <button class="btn btn-primary" type="submit">Save changes</button>
        </div>
    </div>
</div>

resources/views/admin/shoppingboxes/edit.blade.php
@extends('admin.dashboard') 
@section('title', 'Shopping Boxes') 
@section('content')

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>{{ $box->name }}</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/admin') }}">Admin</a>
            </li>
            <li>
                <a href="{{ url('/admin/shopping-boxes') }}">Shopping Boxes</a>
            </li>
            <li class="active">
                <strong>Edit</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">


    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">

    @if(count($errors))

    <div class="alert alert-danger">


        @foreach ($errors->all() as $message) {{ $message }} <br /> @endforeach


    </div>

    @endif 
    
    {{ Form::model( $box, [ 'route' => ['admin.shopping-boxes.update',$box], 'method' => 'patch', 'enctype' => 'multipart/form-data',
    'class' => 'form-horizontal' ] ) }}
    
    @include('admin.shoppingboxes._fields') 
    
    {{ Form::close() }}

</div>
@endsection

resources/views/admin/shoppingboxes/index.blade.php
@extends('admin.dashboard') 
@section('title', 'Shopping Boxes') 
@section('content')

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Shopping Boxes</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url('/admin') }}">Admin</a>
            </li>
            <li class="active">
                <strong>Shopping Boxes</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">


    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

        @foreach($boxes as $box)
        <div class="col-sm-3">
            <div class="ibox">
                <div class="ibox-title text-center">
                    <h3>{{ $box->name }}</h3>
                </div>
                <div class="ibox-content">
                        <div class="row">
                            <div class="col-xs-6">
                                <small class="stats-label">Subscription Boxes</small>
                                <h4>{{ $box->remaining_boxes }}</h4>
                            </div>

                            <div class="col-xs-6">
                                <small class="stats-label">Stocks</small>
                                <h4>{{ $box->stock ?? 'No limit' }}</h4>
                            </div>
                        </div>
                    </div>
                <div class="ibox-content">
                    @if(!empty($box->cover))

                    <img src="{{ $box->cover }} " width="100%" />

                    @endif
                   
                
                </div>
                <div class="ibox-footer text-right">
                    <a href="{{ route('admin.shopping-boxes.edit',['shopping_box' => $box->id]) }}" class="btn btn-primary">Edit</a>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection