routes/web.php
            Route::get('/store/shipping/settings', 'ShippingController@settings');
            Route::post('/store/settings/store_address', 'ShippingController@update_store_address');
            Route::resource('shipping-zones', 'ShippingZoneController');
        });

        Route::namespace ('Settings')->group(function () {
            Route::get('/store/settings/wholesale', 'SettingsController@wholesale');
            Route::patch('/store/settings/wholesale', 'SettingsController@wholesaleUpdate')->name('settings.wholesale.update');
        });

        Route::namespace ('Tools')->group(function () {
            Route::get('/store/tools/export-subscribers', 'ToolsController@export_subscribers')->name('tools.export_subscribers');
        });

        Route::namespace ('Blogs')->group(function () {
            Route::name('blogs.search')->post('/blogs/search', 'BlogSearchController@search');
            Route::name('blogs.get.gallery')->get('/blogs/gallery/{offset}/{skip}', 'BlogAxiosController@getBlog');
            Route::resources([
                'blogs' => 'BlogController',
                'blogtag' => 'BlogTagController',
                'blogtagsgroups' => 'BlogTagsGroupsController',
                'blogdraft' => 'BlogDraftController',
                'blogcategory' => 'BlogCategoryController',
                'bloggallery' => 'BlogImageGalleryController',
                'blogsubcategory' => 'BlogSubCategoryController',
                'blogauthor' => 'BlogAuthorController',
                'blogcategorygroup' => 'BlogCategoryGroupController',
            ]);
        });

        Route::namespace ('Store')->group(function () {
            Route::resources([
                'storelocator' => 'StoreLocatorController',
                'storelocatorimport' => 'StoreImportController',
                'storelocatorshow' => 'StoreShowController',
            ]);
        });
        

        Route::namespace('GiftCards')->group(function () {
            Route::get('/search/gift-cards', 'GiftCardAdminController@index');
            Route::post('/gift-cards/{gift_card}/resend', 'GiftCardAdminController@resend');
            Route::delete('/gift-cards/{gift_card}', 'GiftCardAdminController@remove');
        });

        Route::namespace ('Dashboard')->group(function () {
            Route::get('/', 'AdminController@index')->name('dashboard');
            Route::get('/dashboard/stats', 'AdminController@stats')->name('dashboard.stats');
        });

        Route::namespace ('Blogs')->group(function () {
            Route::name('blogs.search')->post('/blogs/search', 'BlogSearchController@search');
            Route::name('blogs.get.gallery')->get('/blogs/gallery/{offset}/{skip}', 'BlogAxiosController@getBlog');
            Route::resources([
                'blogs' => 'BlogController',
                'blogtag' => 'BlogTagController',
                'blogtagsgroups' => 'BlogTagsGroupsController',
                'blogdraft' => 'BlogDraftController',
                'blogcategory' => 'BlogCategoryController',
                'bloggallery' => 'BlogImageGalleryController',
                'blogsubcategory' => 'BlogSubCategoryController',
                'blogauthor' => 'BlogAuthorController',
                'blogcategorygroup' => 'BlogCategoryGroupController',
            ]);
        });

        Route::namespace ('Pagebuilder')->group(function () {
            Route::get('pagebuilder/editpage/{page}','PagebuilderController@edit_template')->name('pagebuilder.edit_template');
            Route::resource('pagebuilder', 'PagebuilderController',['parameters' => [
                'pagebuilder' => 'page'
            ]]);
        });

    });

    //API

    Route::prefix('api')->group(function(){
        Route::get('productsproducts', function(){
            return App\Shop\Products\Product::active()->get()->map(function($product){
                return [
                    'id' => $product->id,
                    'sku' => $product->sku,
                    'name' => $product->name,
                ];
            });
        });
    });

    Route::group(['namespace' => 'Frontend'], function () {

        Route::namespace ('Pages')->group(function () {

            Route::get('/', 'PageController@index')->name('home');

            Route::prefix('pages')->group(function () {
                Route::get('faqs', 'PageController@faqs')->name('faqs');
                Route::get('become-an-ambassador', 'PageController@ambassador')->name('become-an-ambassador');
                Route::get('wholesale', 'PageController@wholesale_program')->name('wholesale');
                Route::get('our-cause', 'PageController@our_cause')->name('our-cause');
                Route::get('be-a-team-member', 'PageController@careers')->name('be-a-team-member');
                Route::get('dillution-rates', 'PageController@dillution_rates')->name('dillution-rates');
                Route::get('ebook', 'PageController@e_book')->name('ebook');
                Route::get('comparison-blends', 'PageController@comparison_chart')->name('comparison-blends');
                Route::get('6-steps-to-purity', 'PageController@six_steps_to_pure')->name('6-steps-to-purity');
                Route::get('our-story', 'PageController@our_story')->name('our-story');
                Route::get('privacy-policy', 'PageController@privacy_policy')->name('privacy-policy');
                Route::get('terms-of-service', 'PageController@terms_of_use')->name('terms-of-service');
                Route::get('ask-our-aromatherapist', 'PageController@our_aromatherapist')->name('ask-our-aromatherapist');
                Route::get('pure-natural-products', 'PageController@simply_pure_promise')->name('pure-natural-products');
                Route::get('free-returns', 'PageController@free_shipping')->name('free-returns');
                Route::get('terms-of-use', 'PageController@terms-of-use')->name('terms-of-use');
                Route::get('new-wholesaler', 'PageController@wholesalerSalesPage')->name('wholesaler.sales');
            });

            Route::get('blogs/stories/', 'BlogController@index')->name('all.blog');
            Route::get('blogs/stories/{slug}', 'BlogController@show')->name('single.post');
            Route::get('blogs/stories/category/{category}', 'BlogController@catFilter')->name('blog.cat.filter');
            Route::get('blogs/stories/tag/{tag}', 'BlogController@tagFilter')->name('blog.tag.filter');
        });

        Route::namespace ('Store')->group(function () {
            Route::name('store.search')->get('/store/search', 'StoreSearchController@search');
            Route::get('/store-locator', 'StoreLocator@index')->name('store-locator');
            Route::get('/store/get/xml', 'StoreLocator@getXml');
        });

        Route::namespace ('Customers')->group(function () {

            Route::get('login', 'CustomerLoginController@showLoginForm')->name('customer.login');
            Route::post('login', 'CustomerLoginController@login');
            Route::post('logout', 'CustomerLoginController@logout')->name('customer.logout');

            //Activation
            Route::get('activation/{token}', 'CustomerRegisterController@activation')->name('activation');

            Route::get('password/reset', 'CustomerForgotPasswordController@showLinkRequestForm')->name('customer.password.request');
            Route::post('password/email', 'CustomerForgotPasswordController@sendResetLinkEmail')->name('customer.password.email');
            Route::get('password/reset/{token}', 'CustomerResetPasswordController@showResetForm')->name('customer.password.reset');
            Route::post('password/reset', 'CustomerResetPasswordController@reset')->name('customer.password.reset_submit');

            // Registration Routes...
            Route::get('register', 'CustomerRegisterController@showRegistrationForm')->name('customer.register');
            Route::post('register', 'CustomerRegisterController@register');

            //Profile

            Route::get('/profile', 'CustomerProfileController@show')->name('profile');
            Route::patch('/profile/address', 'CustomerProfileController@updateAddress')->name('profile.update.address');
            Route::patch('/profile/email', 'CustomerProfileController@updateEmail')->name('profile.update.email');
            Route::patch('/profile/password', 'CustomerProfileController@updatePassword')->name('profile.update.password');
            Route::patch('/profile/payment', 'CustomerProfileController@updatePayment')->name('profile.update.payment');

            // Orders
            Route::get('/past-orders', 'CustomerOrdersController@index')->name('past-orders');
            Route::get('/past-orders/{order}', 'CustomerOrdersController@order')->name('past-orders.order');
            Route::get('/future-orders', 'CustomerOrdersController@future')->name('future-orders');

            //Rewards
            Route::get('/rewards', 'CustomerProfileController@rewards')->name('rewards');
            Route::post('/rewards/{reward}/claim', 'CustomerProfileController@claimReward')->name('rewards');
            Route::post('/rewards/claim/freebox', 'CustomerProfileController@claimFreebox')->name('rewards');
            Route::post('/rewards/unclaim/freebox', 'CustomerProfileController@unclaimFreebox')->name('rewards');

            //Wholesale
            Route::get('/wholesaler/form', 'WholesalerController@form')->name('wholesaler.form');
            Route::post('/wholesaler/form', 'WholesalerController@checkout')->name('wholesaler.form.checkout');
            Route::get('/wholesaler/create', 'WholesalerController@typeform');
            Route::get('/wholesaler/verify/{email}/{token}', 'WholesalerController@verify')->name('wholesaler.verify');
        });

        Route::namespace ('Products')->group(function () {
            Route::get('/products-feed.xml', 'ProductsController@feed');

app/Models/Pagebuilder/Category.php
<?php

namespace App\Models\Pagebuilder;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'pagebuilder_categories';

    protected $fillable = [
        'name',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function templates()
    {
        return $this->hasMany(Template::class, 'section', 'slug');
    }
}

app/Models/Pagebuilder/MetaData.php
<?php

namespace App\Models\Pagebuilder;

use Illuminate\Database\Eloquent\Model;

class MetaData extends Model
{
    protected $table = 'meta_data';

    protected $fillable = [
        'name',
        'value'
    ];

    public function metadatatable()
    {
        return $this->morphTo();
    }
}

app/Models/Pagebuilder/Page.php
<?php

namespace App\Models\Pagebuilder;

use App\Traits\MetaData;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Page extends Model
{
    use MetaData;

    protected $table = 'pagebuilder_pages';

    protected $fillable = [
        'title',
        'slug',
        'header',
        'footer',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function contents()
    {
        return $this->belongsToMany(Template::class, 'pagebuilder_contents', 'page_id', 'template_id')
            ->withPivot(['content', 'rang'])
            ->orderBy('pagebuilder_contents.rang');
    }

    public function getCacheKey()
    {
        return sprintf(
            "%s/%s-%s",
            $this->getTable(),
            $this->getKey(),
            $this->updated_at->timestamp
        );
    }

    public function clearCache()
    {
        return Cache::forget($this->getCacheKey());
    }
}

app/Models/Pagebuilder/Pivots/Content.php
<?php

namespace App\Models\Pagebuilder\Pivots;

use Illuminate\Database\Eloquent\Relations\Pivot;

class Content extends Pivot
{
    protected $table = 'pagebuilder_contents';

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $casts  = [
        'content' => 'array'
    ];
}

app/Http/Controllers/Admin/Pagebuilder/PagebuilderController.php
<?php

namespace App\Http\Controllers\Admin\Pagebuilder;

use App\Models\Pagebuilder\Page;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PagebuilderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pages = Page::query();
        if($request->has('q')){
            $pages->where('title', 'LIKE', "%".$request->q."%");
        }
        $pages = $pages->paginate(10);

        return view('admin/pagebuilder/index', compact('pages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/pagebuilder/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $page = Page::make($request->all());
        $page->save();

        if ($request->has('meta_title')) {
            $page->metaData()->create([
                'name' => 'title',
                'value' => $request->meta_title,
            ]);
        }

        if ($request->has('meta_description')) {
            $page->metaData()->create([
                'name' => 'description',
                'value' => $request->meta_description,
            ]);
        }

        flash('Page create', 'success');

        return redirect()->route('admin.pagebuilder.edit_template', $page ?? collect());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Page $page)
    {
        return view('admin/pagebuilder/edit', compact('page'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Page $page)
    {
        $page->fill($request->all());
        $page->save();

        if ($request->has('meta_title')) {
            $page->metaData()->updateOrCreate([
                'name' => 'title'
            ], [
                'value' => $request->meta_title,
            ]);
        }

        if ($request->has('meta_description')) {
            $page->metaData()->updateOrCreate([
                'name' => 'description',
            ], [
                'value' => $request->meta_description,
            ]);
        }

//        flash('Page updated', 'success');

        return redirect()->route('admin.pagebuilder.index')->with('Page updated', 'success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Page $page)
    {
        $page->delete();
        return redirect()->route('admin.pagebuilder.index')->with('Page deleted', 'success');
    }

    public function edit_template(Page $page){
        return view('admin/pagebuilder/template', compact('page'));
    }
}

app/Http/Controllers/Api/Pagebuilder/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Pagebuilder;

use App\Http\Resources\Pagebuilder\CategoryCollection;
use App\Models\Pagebuilder\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function __invoke()
    {
        return new CategoryCollection(Category::all());
    }
}

app/Http/Controllers/Api/Pagebuilder/TemplateController.php
<?php

namespace App\Http\Controllers\Api\Pagebuilder;

use App\Http\Resources\Pagebuilder\CategoryCollection;
use App\Http\Resources\PageResource;
use App\Models\Pagebuilder\Category;
use App\Models\Pagebuilder\Page;
use App\Models\Pagebuilder\Template;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class TemplateController extends Controller
{
    public function show($page)
    {
        /** @var Page $page */
        $page = Page::query()->with('contents')->find($page);

        return Cache::rememberForever($page->getCacheKey(), function () use ($page) {
            return new PageResource($page);
        });
    }

    public function store(Page $page, Request $request)
    {
        $rang = 0;
//        $content = [];

        $page->clearCache();

        $page->fill($request->only(['header', 'footer']));
        $page->save();

        $page->contents()->detach();

        foreach ((array) $request->data as $data) {
            $block = $data['dataObject'];
            $template = Template::find($block['id']);

            $page->contents()->attach($template, [
                'content' => json_encode($block['structure']),
                'rang'    => $rang++,
            ]);
        }

        return response()->json(true);
    }

    public function loadImage(Request $request)
    {
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $directory = 'images/';
            $file_name = md5($file->getFilename().time()).'.'.$file->getClientOriginalExtension();

            \Storage::disk('public')->put($directory.$file_name, \File::get($file));

            return config('app.url').\Storage::url($directory.$file_name);
        }
    }
}

resources/views/admin/pagebuilder/_form.blade.php
<fieldset class="form-horizontal">
    {{ csrf_field() }}
    <div class="form-group">
        <label class="col-sm-2 control-label" for=title"">Title:</label>
        <div class="col-sm-10">
            <input type="text" name="title" class="form-control" placeholder="Title"
                   value="{{old('title') ?? $page->title ?? ""}}">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for=title"">Slug:</label>
        <div class="col-sm-10">
            <input type="text" name="slug" class="form-control" placeholder="Slug page"
                   value="{{old('slug', $page->slug ?? "")}}">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for=title"">Meta title:</label>
        <div class="col-sm-10">
            <input type="text" name="meta_title" class="form-control" placeholder="Meta title"
                   value="{{old('meta_title', $page->meta_title->value ?? "")}}">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label" for=title"">Meta description:</label>
        <div class="col-sm-10">
            <textarea class="form-control" name="meta_description" id="" cols="30" rows="5"
                      placeholder="Meta description">{{old('meta_description', $page->meta_description->value ?? "")}}</textarea>
        </div>
    </div>
    @isset($page)
        <div class="form-group">
            <label class="col-sm-2 control-label" for=title"">Page content:</label>
            <div class="col-sm-10">
                <a href="{{route('admin.pagebuilder.edit_template', $page ?? collect())}}" class="btn btn-primary">Edit Content</a>
            </div>
        </div>
    @endisset
</fieldset>

@push('footer_scripts')
    <script>

        let parent;
        let elem;
        let clone;
        let list;
        // let divForm = document.createElement('div');
        // let divCol3 = document.createElement('div');
        // let divCol7 = document.createElement('div');
        // let label = document.createElement('label');
        // let inputName = document.createElement('input');
        // let inputLink = document.createElement('input');
        // divForm.classList.add('form-group redirect');
        let addLink;
        setTimeout(() => (
            addLink = document.querySelector('.add-link'),
                addLink.addEventListener('click', () => {
                    list = document.querySelectorAll('.redirect').length,
                        console.log(list);
                    parent = document.querySelector('.redirects');
                    elem = parent.querySelector('.redirect');
                    clone = elem.cloneNode(true);
                    clone.querySelectorAll('.form-control').forEach(function (e, index) {

                        e.setAttribute('name', 'redirects[' + list + '][' + (index == 0 ? 'utm_content' : 'url') + ']');
                        e.value = '';
                    });
                    console.log(clone);
                    parent.appendChild(clone);
                })
        ), 1000);


    </script>
@endpush

resources/views/admin/pagebuilder/create.blade.php
@extends('admin.dashboard')
@section('title', 'Create New Page')
@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Page</h2>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}">Admin</a></li>
                <li><a href="{{ route('admin.pagebuilder.index') }}">Pages</a></li>
                <li class="active"><strong>Add new</strong></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('admin.layouts.errors') @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
                <a href="{{ route('admin.blogs.index') }}">
                    <button type="button" class="btn btn-default">All Pages</button>
                </a>
            </div>
        @endif

        <div class="row">
            <div class="col-lg-12">
                <form action="{{route('admin.pagebuilder.store')}}" method="POST">
                    <div class="tabs-container">
                        <div class="tab-content">
                            <div id="blog" class="tab-pane active">
                                <div class="panel-body">
                                    @include('admin/pagebuilder/_form')
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for=title""></label>
                                        <div class="col-sm-10">
                                            <a href="{{route('admin.pagebuilder.index')}}" class="btn btn-default pull-right">Back</a>
                                            <button type="submit" class="btn btn-primary pull-right m-r-sm">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection

@section('js')
{{--    <script src="{{ mix('js/admin-blog.js') }}" charset="utf-8"></script>--}}
@endsection

resources/views/admin/pagebuilder/edit.blade.php
@extends('admin.dashboard')
@section('title', 'Create New Page')
@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Page</h2>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}">Admin</a></li>
                <li><a href="{{ route('admin.pagebuilder.index') }}">Pages</a></li>
                <li class="active"><strong>Edit page</strong></li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('admin.layouts.errors') @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
                <a href="{{ route('admin.blogs.index') }}">
                    <button type="button" class="btn btn-default">All Pages</button>
                </a>
            </div>
        @endif

        <div class="row">
            <div class="col-lg-12">
                <form action="{{route('admin.pagebuilder.update', $page)}}" method="POST">
                    {{ method_field('PUT') }}
                    <div class="tabs-container">
                        <div class="tab-content">
                            <div id="blog" class="tab-pane active">
                                <div class="panel-body">
                                    @include('admin/pagebuilder/_form')
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for=title""></label>
                                        <div class="col-sm-10">
                                            <a href="{{route('admin.pagebuilder.index')}}" class="btn btn-default pull-right">Back</a>
                                            <button type="submit" class="btn btn-primary pull-right m-r-sm">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection

@section('js')
{{--    <script src="{{ mix('js/admin-blog.js') }}" charset="utf-8"></script>--}}
@endsection

resources/views/admin/pagebuilder/index.blade.php
@extends('admin.dashboard') 
@section('title', 'All Post') 
@section('content')

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>All Post</h2>
    <ol class="breadcrumb">
      <li> <a href="{{ url('/admin') }}">Admin</a> </li>
      <li> <a href="#">Pages</a> </li>
      <li class="active"> <strong>All Pages</strong> </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">

  @if (session('success'))
  <div class="alert alert-success">{{ session('success') }}</div>
  @endif @if (isset($success))
  <div class="alert alert-success">{{ $success }}</div>
  @endif

  <div id="delete-alert"></div>

  <div class="ibox-content m-b-sm border-bottom">
    <div class="row">
      <div class="col-sm-6">
        <form action="{{ route('admin.pagebuilder.index') }}" class="form-inline">
          <div class="form-group">
          <input class="form-control" placeholder="Search Page" name="q" value=" {{ request()->get('q', '') }}" type="text">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
          </div>
        </form>
      </div>
      <div class="col-sm-6">
        <div class="text-right">
          <a href="{{ route('admin.pagebuilder.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> New Page</a>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-content">
          <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
            <thead>
              <tr>
                <th>Title</th>
                <th>Page slug</th>
                <th width="250px"></th>
              </tr>
            </thead>
            <tbody>
              @foreach ($pages as $key => $page)
              <tr>
                <td>{{ ucwords(str_limit($page->title, 20)) }}</td>
                <td>{{$page->slug}}</td>
                <td>
                  <div>
                    <a href="{{route('page', $page->slug) }}" class="btn btn-outline btn-primary">Show</a>
                    <a href="{{route('admin.pagebuilder.edit', $page) }}" class="btn btn-primary">Edit</a>
                    <a href="{{route('admin.pagebuilder.destroy', $page) }}"
                       onclick="event.preventDefault();
                               if(confirm('Are you sure?')){
                               document.getElementById('delete-form-{{$page->id}}').submit();
                               }"
                       class="btn btn-danger">Delete</a>
                      <form id="delete-form-{{$page->id}}"
                            action="{{ route('admin.pagebuilder.destroy', $page) }}" method="POST"
                            style="display: none;">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                      </form>
                  </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>

          <nav aria-label="Page navigation example">
            {{ $pages->links() }}
          </nav>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection
 
@section('footer_base_scripts')
<script src="{{ asset('js/admin-blog.js') }}" charset="utf-8"></script>
{{--<script type="text/javascript">--}}
{{--  $(document).on('click', '.delete-blog-post', function() {--}}
{{--      let id = $(this).parents('li').data('id');--}}
{{--      let delete_id = "'delete-post'";--}}

{{--      let html =--}}
{{--      '<div class="alert alert-danger">' +--}}
{{--        '<p>You are about to delete a post </p>' +--}}
{{--        '<a href="#" class="btn btn-default" onclick="event.preventDefault(); document.getElementById('+ delete_id +').submit();">' +--}}
{{--          'YES' +--}}
{{--        '</a>' +--}}
{{--        '<a href="#" id="delete-no" class="btn btn-default">NO</a>' +--}}
{{--        '<form id="delete-post" action="/admin/blogs/'+ id +'" method="POST" style="display: none;">' +--}}
{{--          '<?php echo csrf_field(); ?>' +--}}
{{--          '<?php echo method_field('DELETE'); ?>' +--}}
{{--        '</form>'--}}
{{--      '</div>';--}}

{{--      $('#delete-alert').html(html);--}}
{{--    });--}}

{{--    $(document).on('click', '#delete-no', function() {--}}
{{--      $('#delete-alert').html('');--}}
{{--    });--}}

{{--</script>--}}
@endsection